[package]
name = "setup"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
solana-core = "1.7.10"
solana-sdk = "1.7.10"
solana-program = "1.7.10"
solana-streamer = "1.7.10"
spl-token = "*"
borsh = "0.9.1"
spl-associated-token-account = "1.0.3"

[lib]
name = "setup"
